=== eduardoarantes/tears/Configurations/Test/reports/groupByReports/Report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>Esse documento faz parte do sistema de relatórios e
			não pode ser utilizado para outros fins.
			Propriedade de Trigger
			Soluções</xs:documentation>
	</xs:annotation>
	<xs:element name="Reports" type="ReportsType">
		<xs:annotation>
			<xs:documentation>Trigger Easy Application Report
				Sistema de geração
				de automática de relatórios</xs:documentation>
		</xs:annotation>
		<xs:keyref name="reportConnectionIdRefKey" refer="connectionIdKey">
			<xs:selector xpath="Report" />
			<xs:field xpath="@ConnectionId" />
		</xs:keyref>
		<xs:keyref name="defaultConnectionKey" refer="connectionIdKey">
			<xs:selector xpath="Connections" />
			<xs:field xpath="@defaultConnection" />
		</xs:keyref>
		<xs:key name="connectionIdKey">
			<xs:selector xpath=".//Connections/Connection" />
			<xs:field xpath="@Id" />
		</xs:key>
		<xs:key name="reportIdKey">
			<xs:selector xpath="Report" />
			<xs:field xpath="@Id" />
		</xs:key>
	</xs:element>
	<xs:complexType name="RecordsetParametersType">
		<xs:sequence>
			<xs:element name="RSQueryParameters" type="QueryParametersType"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QueryParametersType">
		<xs:sequence>
			<xs:element name="QueryParameter" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="QueryParameterType" />
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QueryParameterType">
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="DefaultValue" type="xs:string" use="optional" />
	</xs:complexType>
	<xs:complexType name="ReportParametersType">
		<xs:sequence>
			<xs:element name="ReportParameter" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ReportParameterType">
							<xs:sequence>
								<xs:element name="ReportParameterMap" minOccurs="0"
									maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="Key" type="xs:string" use="required" />
										<xs:attribute name="MessageKey" type="xs:string"
											use="required" />
									</xs:complexType>
								</xs:element>
								<xs:element name="ReportParameterSql" type="ReportParameterSqlType"
									maxOccurs="1" minOccurs="0">
								</xs:element>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReportParameterType">
		<xs:attribute name="Required" type="xs:string" use="optional"
			default="true" />
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="Type" type="xs:string" />
		<xs:attribute name="Description" type="xs:string" />
		<xs:attribute name="DefaultValue" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="RecordsetType">
		<xs:sequence>
			<xs:element name="Sql" type="xs:string" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="Config" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Content"
							type="xs:string" maxOccurs="1" minOccurs="0">
						</xs:element>
					</xs:sequence>
					<xs:attribute name="Name" type="xs:string"
						use="required" />
					<xs:attribute name="Value" type="xs:string"
						use="optional" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Columns" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Column" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ColumnMap" minOccurs="0"
										maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="Key" type="xs:string" use="required" />
											<xs:attribute name="MessageKey" type="xs:string"
												use="required" />
										</xs:complexType>
									</xs:element>
									<xs:element name="Url" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="UrlParameter" minOccurs="0"
													maxOccurs="unbounded">
													<xs:complexType>
														<xs:simpleContent>
															<xs:extension base="xs:string">
																<xs:attribute name="Name" type="xs:string"
																	use="required" />
															</xs:extension>
														</xs:simpleContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="ReportId" type="xs:string" />
											<xs:attribute name="Description" type="xs:string" />
											<xs:attribute name="Path" type="xs:string" />
											<xs:attribute name="Complement" type="xs:string" />
											<xs:attribute name="NewWindow" type="xs:string"
												default="false" />
											<xs:attribute name="OpenInLine" type="xs:boolean"
												use="optional" default="false">
											</xs:attribute>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="Id" type="xs:string" use="required" />
								<xs:attribute name="Description" type="xs:string"
									use="optional" />
								<xs:attribute name="Type" type="xs:string" default="TEXT" />
								<xs:attribute name="Consolidator" type="xs:string"
									use="optional" />
								<xs:attribute name="MappedDataNotFound" type="xs:string"
									use="optional" />
								<xs:attribute name="Display" type="xs:boolean" use="optional"
									default="true">
								</xs:attribute>
								<xs:attribute name="Format" type="xs:string" use="optional">
									<xs:annotation>
										<xs:documentation>
											allows to format data
										</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="StyleClass" type="xs:string">
								</xs:attribute>
								<xs:attribute name="AllowFilter" type="xs:boolean"
									default="false">
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="GroupBy" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="GroupByColumn"
							maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="RefId"
											type="xs:string" use="required">
										</xs:attribute>
										<xs:attribute name="Id"
											type="xs:string" use="optional">
										</xs:attribute>
										<xs:attribute
											name="Consolidator" type="xs:string" use="optional" />
										<xs:attribute name="Description"
											type="xs:string" use="optional">
										</xs:attribute>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="CalculatedColumn"
							minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="RefId"
											type="xs:string" use="required">
										</xs:attribute>
										<xs:attribute name="Id"
											type="xs:string" use="optional">
										</xs:attribute>
										<xs:attribute name="Type"
											type="xs:string" use="required" />
										<xs:attribute
											name="Consolidator" type="xs:string" use="optional" />
										<xs:attribute name="Description"
											type="xs:string" use="optional">
										</xs:attribute>
										<xs:attribute name="Format"
											type="xs:string">
										</xs:attribute>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="Chart" type="ChartType"
							maxOccurs="1" minOccurs="0">
						</xs:element>
					</xs:sequence>
					<xs:attribute name="Description" type="xs:string"
						use="optional" />
					<xs:attribute name="Id" type="xs:string"
						use="required" />
					<xs:attribute name="Display" type="xs:boolean"
						use="optional" default="true">
					</xs:attribute>
					<xs:attribute name="WithDetails"
						type="xs:boolean">
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Chart" maxOccurs="1" minOccurs="0"
				type="ChartType">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="Description" type="xs:string" />
		<xs:attribute name="DefaultSortColumn" type="xs:string"
			use="optional" />
		<xs:attribute name="RowCountLabel" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					se esse atributo for especificado será criada uma
					coluna com o contador de registros
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="PageSize" type="xs:int" use="optional"></xs:attribute>
		<xs:attribute name="AllowExport" type="xs:string" use="optional"
			default="">
		</xs:attribute>
		<xs:attribute name="Display" type="xs:boolean" use="optional"
			default="true">
		</xs:attribute>
		<xs:attribute name="StyleClass" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ReportsType">
		<xs:sequence>
			<xs:element name="Report" type="ReportType"
				maxOccurs="unbounded">
				<xs:key name="reportParameterIdKey">
					<xs:selector
						xpath="ReportParameters/ReportParameter" />
					<xs:field xpath="@Name" />
				</xs:key>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Version" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ReportType">
		<xs:sequence>
			<xs:element name="ReportParameters" type="ReportParametersType"
				minOccurs="0" />
			<xs:element name="Recordset" type="RecordsetType"
				minOccurs="0" maxOccurs="unbounded">
				<xs:keyref name="ReportParameterKeyRef" refer="ReportParameterKey">
					<xs:selector xpath=".//Reports/Report/Recordset/QueryParameters/*" />
					<xs:field xpath="@Name" />
				</xs:keyref>
				<xs:key name="ReportParameterKey">
					<xs:selector xpath=".//Reports/Report/ReportParameters/ReportParameter" />
					<xs:field xpath="@Name" />
				</xs:key>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Description" type="xs:string" use="optional" />
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="Roles" type="xs:string" use="optional" />
		<xs:attribute name="IsMainReport" type="xs:string" use="optional"
			default="true">
			<xs:annotation>
				<xs:documentation>
					used to hide detailed reports, called from other
					reports
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ExternalLink" type="xs:string" use="optional"
			default="" />
		<xs:attribute name="ConnectionId" type="xs:string" />
		<xs:attribute name="DownloadOnly" type="xs:string"
			default="none" use="optional">
		</xs:attribute>
		<xs:attribute name="TemplateName" type="xs:string"
			default="Default.html" use="optional"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ReportParameterSqlType">
		<xs:annotation>
			<xs:documentation>
				Elemento fornecido para disponibilizar uma lista de valores para
				serem passados como parametro para a query do RecordSet em questão.
				Para configurá-lo corretamente será necessário informar os valores
				dos atributos key e value. Caso não informe algum dos valores,
				o
				mesmo deve ser substituidopor alias na query dentro do
				elemento-filho sql. Exemplos:
				<ReportParameterSql>
					<sql>
		<![CDATA[
			select A as KEY, B as VALUE from c
		]]>
					</sql>
				</ReportParameterSql>
				----------------------------------------------------------
				<ReportParameterSql key="A">
					<sql>
		<![CDATA[
			select A, B as VALUE from c
		]]>
					</sql>
				</ReportParameterSql>
				----------------------------------------------------------
				<ReportParameterSql value="B">
					<sql>
		<![CDATA[
			select A as KEY, B from c
		]]>
					</sql>
				</ReportParameterSql>
				----------------------------------------------------------
				<ReportParameterSql key="A" value="B">
					<sql>
		<![CDATA[
			select A, B from c
		]]>
					</sql>
				</ReportParameterSql>
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="sql" type="xs:string">
				<xs:annotation>
					<xs:documentation></xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="key" type="xs:string"></xs:attribute>
		<xs:attribute name="value" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ParamType">		<xs:attribute name="Name" type="xs:string" use="required" />
		<xs:attribute name="Value" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="ChartType">
		<xs:sequence>
			<xs:element name="ChartColumn" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="RefId" type="xs:string" use="required" />
					<xs:attribute name="Description" type="xs:string" use="optional" />
					<xs:attribute name="Type" type="xs:string" default="TEXT" />
					<xs:attribute name="Format" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>
								allows to format data
							</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Param" type="ParamType" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Type" type="xs:string" use="optional">
		</xs:attribute>
		<xs:attribute name="Title" type="xs:string"></xs:attribute>
		<xs:attribute name="Description" type="xs:string"></xs:attribute>
		<xs:attribute name="Height" type="xs:int"></xs:attribute>
		<xs:attribute name="Width" type="xs:int"></xs:attribute>
	</xs:complexType>
</xs:schema>

=== eduardoarantes/tears/Configurations/Sample/reports/Consolidator/Reports_ConsolidatorWithDetail.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Report.xsd"
	Version="1.0">
	<Report Id="ConsolidatorWithDetails" Title="With Details" Description="Display the products per category">
		<Recordset Id="ProductListGroupBy" DefaultSortColumn="ProductName"
			Description="Simple report. Just list a result of a SQL statement. Test GroupBy"
			PageSize="10" AllowExport="false" Display="false">
			<Sql><![CDATA[
			SELECT DISTINCT Products.ProductID, Products.ProductName, Products.SupplierID, 
			Products.CategoryID, Products.QuantityPerUnit, 
			Products.UnitPrice, Products.UnitsInStock,  Products.Discontinued,
				Categories.CategoryName
				FROM Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID
			]]></Sql>
			<Columns >
				<Column Id="CategoryName" Display="false"/>
				<Column Id="Discontinued" Display="false"/>
				<Column Id="Discontinued" Type="MAPPED" MappedDataNotFound="Undefined">
					<ColumnMap Key="1" MessageKey="Active" />
					<ColumnMap Key="0" MessageKey="Discontinued" />
				</Column>
			</Columns>
			<GroupBy Id="ProductsByCategory" Description="Number of Product by Category" WithDetails="true">
				<GroupByColumn Id="CategoryName" RefId="CategoryName" />
				<GroupByColumn Id="Discontinued" RefId="Discontinued" />
				<CalculatedColumn Id="Products" RefId="ProductID"
					Type="INTEGER" Consolidator="count" Description="#Products" />
				<CalculatedColumn Id="UnitsInStock" RefId="UnitsInStock" Type="INTEGER"
					Consolidator="sum" Description="#UnitsInStock" />
				<CalculatedColumn Id="AverageUnitsInStock" RefId="UnitsInStock"
					Type="DOUBLE" Consolidator="average" Description="#AverageUnitsInStock"
					Format="#.##" />
			</GroupBy>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Sample/reports/AutoFilter/Reports_AutoFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.2/Report.xsd" Version="1.0">
	<Report Id="AutoFilter" Title="Auto filter"
		Description="This report has two columns defined as Autofilter. See configuration file to detail">
		<Recordset Id="AutoFilter" Title="Auto filter" DefaultSortColumn="OrderID"
			Description="This report has two columns defined as Autofilter. See configuration file to detail"
			PageSize="17" AllowExport="none">
			<Sql><![CDATA[SELECT OrderID, CustomerID, EmployeeID, OrderDate, RequiredDate, 
ShippedDate, ShipVia, Freight, ShipName, ShipAddress, ShipCity, 
ShipRegion, ShipPostalCode, ShipCountry FROM Orders 
			]]></Sql>
			<Columns>
				<Column Id="ShipVia" AllowFilter="true" />
				<Column Id="ShipCountry" AllowFilter="true" />
				<Column Id="OrderID" Display="false" />				
			</Columns>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Moodle/reports/Cursos/Reports_categories.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.1/Report.xsd" Version="1.0.1">
	<Report Id="ListadeCategorias" Description="Lista de categorias">
		<Recordset Id="ListaDeCategorias"
			Description="Lista de categoria dos cursos">
			<Sql><![CDATA[
				select id, name, description, coursecount, visible from #{table.prefix}course_categories;
			]]></Sql>
			<Columns>
				<Column Id="id">
					<Url ReportId="ListadeCursos" Description="Clique aqui para listar os cursos dessa categoria">
						<UrlParameter Name="category">id</UrlParameter>
					</Url>
				</Column>
				<Column Id="visible" Description="Visível"
					MappedDataNotFound="Ainda não definido">
					<ColumnMap Key="1" MessageKey="Visível" />
					<ColumnMap Key="0" MessageKey="Oculto" />
				</Column>
				<Column Id="name" Description="Nome"/>
				<Column Id="description" Description="Descrição"/>
				<Column Id="coursecount" Description="Qte de Cursos" Type="INTEGER"/>
			</Columns>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Sample/reports/DataFilter/Reports_DataFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.2/Report.xsd"
	Version="1.0">
	<Report Id="SimpleDateFilter" Title="Simple Date Filter"
		Description="This report has two date filter. You can select on the calendar or type it.">
		<ReportParameters>
			<ReportParameter Id="StartDate" Description="Start Date - Use 1996-07-01"
				Type="DATE" />
			<ReportParameter Id="EndDate" Description="End Date - Use 1996-07-31 "
				Type="DATE" />
		</ReportParameters>
		<Recordset Id="SimpleDateFilter" Title="Simple Date Filter" DefaultSortColumn="OrderID"
			Description="This report has two date filter. You can select on the calendar or type it. Page Size is defined to 10"
			PageSize="10">
			<Sql><![CDATA[select OrderDate, sum(Freight) SumFreight, avg(Freight) AvgFreight
from Orders 
where OrderDate >= #{StartDate} and OrderDate <= #{EndDate} 
group by OrderDate
			]]></Sql>
			<Columns>
				<Column Id="OrderDate" Type="DATE" />
				<Column Id="SumFreight" Type="DOUBLE" />
			</Columns>
		</Recordset>
	</Report>
	<Report Id="DatabaseDropDown" Title="Database DropDown"
		Description="This report has a dropdown filter which values came from database"
		TemplateName="A4Landscape.html">
		<ReportParameters>
			<ReportParameter Id="idShipper" Type="QUERY"
				Description="Select the Shipper">
				<ReportParameterSql>
					<sql><![CDATA[
SELECT ShipperID AS "KEY" , CompanyName "VALUE" FROM Shippers
				]]></sql>
				</ReportParameterSql>
			</ReportParameter>
		</ReportParameters>
		<Recordset Id="DatabaseDropDown" Title="Database DropDown"
			Description="This report has a dropdown filter which values came from database. Freight Column is formated">
			<Sql><![CDATA[SELECT OrderID, CustomerID, OrderDate, RequiredDate, 
ShippedDate, ShipVia, (-1*Freight) Freight, ShipName, 
ShipRegion, ShipPostalCode, ShipCountry FROM Orders 
WHERE ShipVia= #{idShipper}
			]]></Sql>
			<Columns>
				<Column Id="RequiredDate" Type="DATE" Format="yyyy-MM-dd" />
				<Column Id="Freight" Type="DOUBLE" Format="#.##" />
			</Columns>
		</Recordset>
	</Report>
	<Report Id="StaticRadioFilter" Title="Static Radio Filter"
		Description="Static Radio values are fixed in the configuration" TemplateName="A4Landscape.html">
		<ReportParameters>
			<ReportParameter Id="status" Type="RADIO"
				Description="Products status">
				<ReportParameterMap Key="1" MessageKey="Active" />
				<ReportParameterMap Key="0" MessageKey="Discontinued" />
				<ReportParameterMap Key="%" MessageKey="All" />
			</ReportParameter>
		</ReportParameters>
		<Recordset Id="StaticRadioFilter" Title="Static Radio Filter"
			Description="Static Dropdown values are fixed in the configuration. NOTE: Column Status is mapped. Active is 1 and Discontinued is 0">
			<Sql><![CDATA[SELECT DISTINCT Products.*, Categories.CategoryName
FROM Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID
where Discontinued = #{status}
			]]></Sql>
			<Columns>
				<Column Id="Discontinued" Description="ProductStatus" Type="MAPPED" MappedDataNotFound="Undefined">
					<ColumnMap Key="1" MessageKey="Active" />
					<ColumnMap Key="0" MessageKey="Discontinued" />
				</Column>
			</Columns>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Moodle/reports/Atividades/Reports_forum.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.1/Report.xsd"
	Version="1.0.1">
	<Report Id="ForunsPorCurso" Description="Lista de Fórums por curso">
		<ReportParameters>
			<ReportParameter Id="course" Type="QUERY">
				<ReportParameterSql>
					<sql>SELECT id  AS "KEY", shortname as "VALUE" FROM #{table.prefix}course order by shortname</sql>
				</ReportParameterSql>
			</ReportParameter>
		</ReportParameters>
		<Recordset Id="ForunsPorCurso" Description="Lista de Fórums por curso">
			<Sql><![CDATA[
select f.id, f.type, f.name, count(distinct fd.id) discussions, count(fp.discussion) posts
from #{table.prefix}forum f inner join #{table.prefix}forum_discussions fd
on f.id = fd.forum and f.course = fd.course
inner join #{table.prefix}forum_posts fp on fd.id = fp.discussion
where f.course = #{course}
group by f.id, f.type, f.name]]></Sql>
			<Columns>
				<Column Id="type" Description="Tipo" />
				<Column Id="name" Description="Nome" />
				<Column Id="discussions" Description="Discussoes" Type="INTEGER"/>
				<Column Id="posts" Description="Mensagens" Type="INTEGER"/>
			</Columns>
		</Recordset>
	</Report>

</Reports>

=== eduardoarantes/tears/Configurations/Test/reports/xmlVersionConveterReports/Reports_xmlVersionConverter.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0/Report.xsd" Version="1.0">
	<Report Id="Relatorios_xmlVersionConverter" Description="Relatorios de csv" ConnectionId="csvFiles">
		<Recordset Id="CSVTest" Description="Todos os valores do arquivo">
			<Config Name="Path"><Content>candidatosNaoAvaliados.csv</Content></Config>
		</Recordset>
		<Recordset Id="CSVTestColumns" Description="Todos os valores do arquivo com as colunas configuradas">
			<Config Name="Path"><Content>candidatosNaoAvaliados.csv</Content></Config>
			<Columns>
				<Column Id="ID" Type="INTEGER"/>
				<Column Id="NOME" Type="TEXT"/>
				<Column Id="SOBRENOME" Type="TEXT"/>
				<Column Id="APELIDO" Type="TEXT"/>
				<Column Id="SEXO" Type="TEXT"/>
				<Column Id="IDENTIDADE" Type="TEXT"/>
				<Column Id="TIPO_IDENTIDADE" Type="TEXT"/>
				<Column Id="CPF" Type="TEXT"/>
				<Column Id="EMAIL" Type="TEXT"/>
				<Column Id="TIPOLOGRADOURO" Type="TEXT"/>
				<Column Id="LOGRADOURO" Type="TEXT"/>
				<Column Id="COMPLEMENTO" Type="TEXT"/>
				<Column Id="BAIRRO" Type="TEXT"/>
				<Column Id="CIDADE" Type="TEXT"/>
				<Column Id="CEP" Type="INTEGER"/>
				<Column Id="ESTADO" Type="TEXT"/>
				<Column Id="TELEFONE" Type="TEXT"/>
				<Column Id="ESCOLARIDADE" Type="TEXT"/>
				<Column Id="PROFISSAO" Type="TEXT"/>
				<Column Id="RENDA_FAMILIAR" Type="TEXT"/>
				<Column Id="AREA_ATUACAO" Type="TEXT"/>
				<Column Id="TIPO_ACESSO_WEB" Type="TEXT"/>
				<Column Id="IDIOMA" Type="TEXT"/>
				<Column Id="TELEFONE2" Type="TEXT"/>
				<Column Id="CARGO" Type="TEXT"/>
				<Column Id="ESTABELECIMENTO" Type="TEXT"/>
				<Column Id="ACESSA_WEB" Type="TEXT"/>
				<Column Id="LOCAL_ACESSO_WEB" Type="TEXT"/>
				<Column Id="ID_CIDADE" Type="TEXT"/>
				<Column Id="DATA_CADASTRO" Type="DATE" Format="dd-MM-yyyy"/>
				<Column Id="CONTATO" Type="TEXT"/>
				<Column Id="TELEFONE_EMPRESA" Type="TEXT"/>
			</Columns>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Moodle/reports/Questionario/Reports_Questionarios.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.1/Report.xsd"
	Version="1.0.1">
	<Report Id="ListadeQuestionarios" Description="Lista de questionários por curso">
		<ReportParameters>
			<ReportParameter Id="course" Type="QUERY">
				<ReportParameterSql>
					<sql>SELECT id  AS "KEY", shortname as "VALUE" FROM #{table.prefix}course order by shortname</sql>
				</ReportParameterSql>
			</ReportParameter>
		</ReportParameters>
		<Recordset Id="ListadeQuestionarios" Description="Lista de questionários por curso">
			<Sql><![CDATA[
			SELECT distinct quiz.id, quiz.name
            FROM #{table.prefix}quiz as quiz, 
            	#{table.prefix}quiz_grades AS grades
            WHERE
            quiz.course = #{course} AND 
            grades.quiz = quiz.id
            ORDER BY quiz.name
			]]></Sql>
			<Columns>
				<Column Id="id">
					<Url ReportId="ResultadoPorQuestionario">
						<UrlParameter Name="quizId">id</UrlParameter>
					</Url>
				</Column>
				<Column Id="name" Description="Nome" />
			</Columns>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Fisgo/reports/Reports_Chart.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0/Report.xsd"
	Version="1.0">
	<Report Id="RedirectsDiaProvider" Description="Redirects por dia por Provider">
		<ReportParameters>
			<ReportParameter Id="idProvider" Type="QUERY"
				Description="Selecione o Provider">
				<ReportParameterSql>
					<sql><![CDATA[
SELECT id AS "KEY" , nome "VALUE" FROM site
				]]></sql>
				</ReportParameterSql>
			</ReportParameter>
		</ReportParameters>
		<Recordset Id="RedirectsDiaProvider" Description="Redirects por dia por Provider" Display="false">
			<Sql><![CDATA[select data, count(*) Total
from redirect r
where siteid = #{idProvider}
group by data
]]></Sql>
			<Columns>
				<Column Id="data" Description="Data" Type="DATE" />
				<Column Id="Count" Type="TEXT" Value="Detalhes"/>
			</Columns>
			<Chart Type="MotionChart">
				<ChartColumn RefId="Count" />
				<ChartColumn RefId="data" />
				<ChartColumn RefId="Total" />
			</Chart>

	
		</Recordset>
	</Report>

</Reports>
