=== eduardoarantes/tears/Configurations/Test/reports/groupByReports/Report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>Esse documento faz parte do sistema de relatórios e
			não pode ser utilizado para outros fins.
			Propriedade de Trigger
			Soluções</xs:documentation>
	</xs:annotation>
	<xs:element name="Reports" type="ReportsType">
		<xs:annotation>
			<xs:documentation>Trigger Easy Application Report
				Sistema de geração
				de automática de relatórios</xs:documentation>
		</xs:annotation>
		<xs:keyref name="reportConnectionIdRefKey" refer="connectionIdKey">
			<xs:selector xpath="Report" />
			<xs:field xpath="@ConnectionId" />
		</xs:keyref>
		<xs:keyref name="defaultConnectionKey" refer="connectionIdKey">
			<xs:selector xpath="Connections" />
			<xs:field xpath="@defaultConnection" />
		</xs:keyref>
		<xs:key name="connectionIdKey">
			<xs:selector xpath=".//Connections/Connection" />
			<xs:field xpath="@Id" />
		</xs:key>
		<xs:key name="reportIdKey">
			<xs:selector xpath="Report" />
			<xs:field xpath="@Id" />
		</xs:key>
	</xs:element>
	<xs:complexType name="RecordsetParametersType">
		<xs:sequence>
			<xs:element name="RSQueryParameters" type="QueryParametersType"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QueryParametersType">
		<xs:sequence>
			<xs:element name="QueryParameter" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="QueryParameterType" />
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QueryParameterType">
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="DefaultValue" type="xs:string" use="optional" />
	</xs:complexType>
	<xs:complexType name="ReportParametersType">
		<xs:sequence>
			<xs:element name="ReportParameter" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ReportParameterType">
							<xs:sequence>
								<xs:element name="ReportParameterMap" minOccurs="0"
									maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="Key" type="xs:string" use="required" />
										<xs:attribute name="MessageKey" type="xs:string"
											use="required" />
									</xs:complexType>
								</xs:element>
								<xs:element name="ReportParameterSql" type="ReportParameterSqlType"
									maxOccurs="1" minOccurs="0">
								</xs:element>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReportParameterType">
		<xs:attribute name="Required" type="xs:string" use="optional"
			default="true" />
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="Type" type="xs:string" />
		<xs:attribute name="Description" type="xs:string" />
		<xs:attribute name="DefaultValue" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="RecordsetType">
		<xs:sequence>
			<xs:element name="Sql" type="xs:string" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="Config" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Content"
							type="xs:string" maxOccurs="1" minOccurs="0">
						</xs:element>
					</xs:sequence>
					<xs:attribute name="Name" type="xs:string"
						use="required" />
					<xs:attribute name="Value" type="xs:string"
						use="optional" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Columns" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Column" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ColumnMap" minOccurs="0"
										maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="Key" type="xs:string" use="required" />
											<xs:attribute name="MessageKey" type="xs:string"
												use="required" />
										</xs:complexType>
									</xs:element>
									<xs:element name="Url" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="UrlParameter" minOccurs="0"
													maxOccurs="unbounded">
													<xs:complexType>
														<xs:simpleContent>
															<xs:extension base="xs:string">
																<xs:attribute name="Name" type="xs:string"
																	use="required" />
															</xs:extension>
														</xs:simpleContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="ReportId" type="xs:string" />
											<xs:attribute name="Description" type="xs:string" />
											<xs:attribute name="Path" type="xs:string" />
											<xs:attribute name="Complement" type="xs:string" />
											<xs:attribute name="NewWindow" type="xs:string"
												default="false" />
											<xs:attribute name="OpenInLine" type="xs:boolean"
												use="optional" default="false">
											</xs:attribute>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="Id" type="xs:string" use="required" />
								<xs:attribute name="Description" type="xs:string"
									use="optional" />
								<xs:attribute name="Type" type="xs:string" default="TEXT" />
								<xs:attribute name="Consolidator" type="xs:string"
									use="optional" />
								<xs:attribute name="MappedDataNotFound" type="xs:string"
									use="optional" />
								<xs:attribute name="Display" type="xs:boolean" use="optional"
									default="true">
								</xs:attribute>
								<xs:attribute name="Format" type="xs:string" use="optional">
									<xs:annotation>
										<xs:documentation>
											allows to format data
										</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="StyleClass" type="xs:string">
								</xs:attribute>
								<xs:attribute name="AllowFilter" type="xs:boolean"
									default="false">
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="GroupBy" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="GroupByColumn"
							maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="RefId"
											type="xs:string" use="required">
										</xs:attribute>
										<xs:attribute name="Id"
											type="xs:string" use="optional">
										</xs:attribute>
										<xs:attribute
											name="Consolidator" type="xs:string" use="optional" />
										<xs:attribute name="Description"
											type="xs:string" use="optional">
										</xs:attribute>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="CalculatedColumn"
							minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="RefId"
											type="xs:string" use="required">
										</xs:attribute>
										<xs:attribute name="Id"
											type="xs:string" use="optional">
										</xs:attribute>
										<xs:attribute name="Type"
											type="xs:string" use="required" />
										<xs:attribute
											name="Consolidator" type="xs:string" use="optional" />
										<xs:attribute name="Description"
											type="xs:string" use="optional">
										</xs:attribute>
										<xs:attribute name="Format"
											type="xs:string">
										</xs:attribute>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="Chart" type="ChartType"
							maxOccurs="1" minOccurs="0">
						</xs:element>
					</xs:sequence>
					<xs:attribute name="Description" type="xs:string"
						use="optional" />
					<xs:attribute name="Id" type="xs:string"
						use="required" />
					<xs:attribute name="Display" type="xs:boolean"
						use="optional" default="true">
					</xs:attribute>
					<xs:attribute name="WithDetails"
						type="xs:boolean">
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Chart" maxOccurs="1" minOccurs="0"
				type="ChartType">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="Description" type="xs:string" />
		<xs:attribute name="DefaultSortColumn" type="xs:string"
			use="optional" />
		<xs:attribute name="RowCountLabel" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					se esse atributo for especificado será criada uma
					coluna com o contador de registros
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="PageSize" type="xs:int" use="optional"></xs:attribute>
		<xs:attribute name="AllowExport" type="xs:string" use="optional"
			default="">
		</xs:attribute>
		<xs:attribute name="Display" type="xs:boolean" use="optional"
			default="true">
		</xs:attribute>
		<xs:attribute name="StyleClass" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ReportsType">
		<xs:sequence>
			<xs:element name="Report" type="ReportType"
				maxOccurs="unbounded">
				<xs:key name="reportParameterIdKey">
					<xs:selector
						xpath="ReportParameters/ReportParameter" />
					<xs:field xpath="@Name" />
				</xs:key>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Version" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ReportType">
		<xs:sequence>
			<xs:element name="ReportParameters" type="ReportParametersType"
				minOccurs="0" />
			<xs:element name="Recordset" type="RecordsetType"
				minOccurs="0" maxOccurs="unbounded">
				<xs:keyref name="ReportParameterKeyRef" refer="ReportParameterKey">
					<xs:selector xpath=".//Reports/Report/Recordset/QueryParameters/*" />
					<xs:field xpath="@Name" />
				</xs:keyref>
				<xs:key name="ReportParameterKey">
					<xs:selector xpath=".//Reports/Report/ReportParameters/ReportParameter" />
					<xs:field xpath="@Name" />
				</xs:key>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Description" type="xs:string" use="optional" />
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="Roles" type="xs:string" use="optional" />
		<xs:attribute name="IsMainReport" type="xs:string" use="optional"
			default="true">
			<xs:annotation>
				<xs:documentation>
					used to hide detailed reports, called from other
					reports
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ExternalLink" type="xs:string" use="optional"
			default="" />
		<xs:attribute name="ConnectionId" type="xs:string" />
		<xs:attribute name="DownloadOnly" type="xs:string"
			default="none" use="optional">
		</xs:attribute>
		<xs:attribute name="TemplateName" type="xs:string"
			default="Default.html" use="optional"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ReportParameterSqlType">
		<xs:annotation>
			<xs:documentation>
				Elemento fornecido para disponibilizar uma lista de valores para
				serem passados como parametro para a query do RecordSet em questão.
				Para configurá-lo corretamente será necessário informar os valores
				dos atributos key e value. Caso não informe algum dos valores,
				o
				mesmo deve ser substituidopor alias na query dentro do
				elemento-filho sql. Exemplos:
				<ReportParameterSql>
					<sql>
		<![CDATA[
			select A as KEY, B as VALUE from c
		]]>
					</sql>
				</ReportParameterSql>
				----------------------------------------------------------
				<ReportParameterSql key="A">
					<sql>
		<![CDATA[
			select A, B as VALUE from c
		]]>
					</sql>
				</ReportParameterSql>
				----------------------------------------------------------
				<ReportParameterSql value="B">
					<sql>
		<![CDATA[
			select A as KEY, B from c
		]]>
					</sql>
				</ReportParameterSql>
				----------------------------------------------------------
				<ReportParameterSql key="A" value="B">
					<sql>
		<![CDATA[
			select A, B from c
		]]>
					</sql>
				</ReportParameterSql>
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="sql" type="xs:string">
				<xs:annotation>
					<xs:documentation></xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="key" type="xs:string"></xs:attribute>
		<xs:attribute name="value" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ParamType">		<xs:attribute name="Name" type="xs:string" use="required" />
		<xs:attribute name="Value" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="ChartType">
		<xs:sequence>
			<xs:element name="ChartColumn" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="RefId" type="xs:string" use="required" />
					<xs:attribute name="Description" type="xs:string" use="optional" />
					<xs:attribute name="Type" type="xs:string" default="TEXT" />
					<xs:attribute name="Format" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>
								allows to format data
							</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Param" type="ParamType" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Type" type="xs:string" use="optional">
		</xs:attribute>
		<xs:attribute name="Title" type="xs:string"></xs:attribute>
		<xs:attribute name="Description" type="xs:string"></xs:attribute>
		<xs:attribute name="Height" type="xs:int"></xs:attribute>
		<xs:attribute name="Width" type="xs:int"></xs:attribute>
	</xs:complexType>
</xs:schema>

=== eduardoarantes/tears/Configurations/Moodle/reports/Cursos/Reports_dialogues.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.1/Report.xsd"
	Version="1.0.1">
	<Report Id="ListadeDialogos" Description="Lista de Dialogos">
		<ReportParameters>
			<ReportParameter Id="course" Type="STRING"
				Required="false" DefaultValue="%" Description="Nome do dialogo" />
		</ReportParameters>
		<Recordset Id="ListadeDialogos" Description="Lista de Dialogos">
			<Sql><![CDATA[
			SELECT id, name FROM #{table.prefix}dialogue where course = #{course};			
			]]></Sql>
			<Columns>
				<Column Id="id" >
				</Column>
				<Column Id="name" Description="Nome" />
			</Columns>
		</Recordset>
	</Report>

</Reports>

=== eduardoarantes/tears/Configurations/Test/reports/Reports_ExpensiveProducts.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0/Report.xsd" Version="1.0">
	<Report Id="TenMostExpensiveProducts" Description="Ten Most Expensive Products">
		<Recordset Id="TenMostExpensiveProducts" Description="Ten Most Expensive Products">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,10			]]></Sql>
		</Recordset>
	</Report>
	<Report Id="PDFSample" Description="Relatório que exibe a lista dos 10 produtos mais caros"  Title="Ten Most Expensive Products" TemplateName="PDFSample.html">
		<Recordset Id="TenMostExpensiveProductsDefault" Description="Descrição da tabela" >
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
		<Chart Description="Gráfico da tabela acima"/>
		</Recordset>
	</Report>
	<Report Id="ChartSample" Description="Ten Most Expensive Products" TemplateName="TesteCss3.html">
		<Recordset Id="TenMostExpensiveProductsDefault" Description="Ten Most Expensive Products" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
		<Chart/>
		</Recordset>
		<Recordset Id="TenMostExpensiveProductsPie" Description="Ten Most Expensive Products" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
		<Chart Type="pie"/>
		</Recordset>
		<Recordset Id="TenMostExpensiveProductsLine" Description="Ten Most Expensive Products" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
		<Chart Type="line"/>
		</Recordset>
		<Recordset Id="TenMostExpensiveProductsBar" Description="Ten Most Expensive Products" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
		<Chart Type="bar"/>
		</Recordset>
		<Recordset Id="TenMostExpensiveProductsColumn" Description="Ten Most Expensive Products" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
		<Chart Type="column"/>
		</Recordset>
	</Report>	
	
	
</Reports>

=== eduardoarantes/tears/Configurations/Uses/reports/SupplyChain/Estoque/Reports_Categories.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.1/Report.xsd"
	Version="1.0.1">
	<Report Id="Categorias" Description="Lista de Categorias de Produtos">
		<Recordset Id="Categorias" Description="Lista de Categorias de Produtos">
			<Sql><![CDATA[SELECT CategoryID, CategoryName, Description
FROM Categories
			]]></Sql>
			<Columns>
				<Column Id="CategoryID" Description="Id" Type="INTEGER">
					<Url ReportId="ProdutosPorCategoria"
						Description="Clique aqui para ver a lista de produtos dessa categoria">
						<UrlParameter Name="categoryID">CategoryID</UrlParameter>
					</Url>
				</Column>
				<Column Id="CategoryName" Description="Nome Categoria" />
				<Column Id="Description" Description="Descrição" />
			</Columns>
		</Recordset>

	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Sample/reports/DrillDown/Reports_ProductsListByCategory.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0/Report.xsd" Version="1.0">
	<Report Id="ProductListByCategory" Description="This report is not available at the report list"
		IsMainReport="false">
		<ReportParameters>
			<ReportParameter Id="categoryID" Required="true"
				Description="Category Id" Type="INTEGER" />
		</ReportParameters>
		<Recordset Id="ProductListByCategory" DefaultSortColumn="ProductName"
			Description="Click on the SupplierID to see supplier data">
			<Sql><![CDATA[SELECT DISTINCT Products.*, Categories.CategoryName
FROM Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID
WHERE Categories.CategoryID = #{categoryID}
			]]></Sql>
			<Columns>
				<Column Id="ProductID" Type="INTEGER" StyleClass="COLORED_NUMBER"/>
				<Column Id="SupplierID" Type="INTEGER" StyleClass="COLORED_NUMBER">
					<Url ReportId="Supplier" OpenInLine="true" Description="click here to see supplier details">
						<UrlParameter Name="supplierID">SupplierID</UrlParameter>
					</Url>
				</Column>
				<Column Id="Discontinued" Description="MappedColumn" Type="TEXT" MappedDataNotFound="Undefined">
					<ColumnMap Key="1" MessageKey="Active" />
					<ColumnMap Key="0" MessageKey="Discontinued" />
				</Column>
			</Columns>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Test/reports/Supplier/Reports_Suppliers.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.1/Report.xsd" Version="1.0.1">
	<Report Id="SupplierList" 
		Description="Alphabetical List of Suppliers" >
		<Recordset Id="SupplierList" DefaultSortColumn="CompanyName"
			Description="Simple SQL" AllowExport="csv,pdf" StyleClass="RecordSetClass">
			<Sql><![CDATA[SELECT SupplierID, CompanyName, ContactName, ContactTitle
, Address, City, Region, PostalCode, Country, Phone, Fax, HomePage
FROM Suppliers
			]]></Sql>
		<Columns>
			<Column Id="SupplierID" StyleClass="ColumnClass">
				<Url ReportId="SupplierList"
					Description="Click here to see Product list for this category">
				</Url>
				<Url ReportId="SupplierList"
					Description="Click here to see Product list for this category">
				</Url>
				<Url ReportId="SupplierList"
					Description="Click here to see Product list for this category">
				</Url>
			</Column>
		</Columns>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Sample/reports/PDF_Generator/Reports_PDF.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.1/Report.xsd"
	Version="1.0">
	<Report Id="PDFSample"
		Description="Relatório que exibe a lista dos 10 produtos mais caros"
		Title="Ten Most Expensive Products" TemplateName="PDF:PDFSample.html">
		<Recordset Id="TenMostExpensiveProductsDefault" Description="Descrição da tabela">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Description="Gráfico da tabela acima" />
		</Recordset>
	</Report>
	<Report Id="PDFSampleAnotherTemplate"
		Description="Relatório que exibe a lista dos 10 produtos mais caros"
		Title="Ten Most Expensive Products" TemplateName="PDFSample2.html">
		<Recordset Id="TenMostExpensiveProductsDefault" Description="Descrição da tabela">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Description="Gráfico" >
				<Param Name="width" Value="450" ApplyTo="pdf"/>
				<Param Name="height" Value="450" ApplyTo="pdf"/>
			</Chart>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Test/reports/ColumnCalculate/Reports_Style_Expression.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0/Report.xsd" Version="1.0">
	<Report Id="StyleExpression" Description="Alphabetical List of Category" >
		<Recordset Id="StyleExpression" DefaultSortColumn="CategoryName"
			Description="Simple SQL with explicit columns definitions. It also has a URL to another report">
			<Sql><![CDATA[SELECT CategoryID, CategoryName, Description
FROM Categories
			]]></Sql>
			<Columns>
				<Column Id="CategoryID" Description="Id" Type="DOUBLE" Format="##.00">
					<Url ReportId="ProductListByCategory"
						Description="Click here to see Product list for this category">
						<UrlParameter Name="categoryID">CategoryID</UrlParameter>
					</Url>
				</Column>
				<Column Id="CategoryID" StyleExpression="(CategoryID % 2 == 0? 'background-red':'background-green')">
				</Column>
				<Column Id="DoubleId" Expression="(CategoryID * CategoryID)" StyleExpression="(CategoryID % 2 == 0? 'font-red ':'font-green ')">
				</Column>
				<Column Id="SumColumn" Value="test" StyleExpression="((DoubleId + CategoryID) > 14? 'font-yellow bold':'font-red italic')">
				</Column>
				<Column Id="TreeColors" Expression="(CategoryID)" StyleExpression="((CategoryID * 2) % 3 == 0? 'background-red font-green':((CategoryID * 2) % 3 == 1?'background-green font-yellow':'background-yellow font-red'))">
				</Column>
			</Columns>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Sample/reports/Consolidator/Reports_Consolidator.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0/Report.xsd" Version="1.0">
	<Report Id="ConsolidatorWithoutDetails" Description="Display the products per category">
		<Recordset Id="OriginalData"
			Description="The consolidator is on the table below"
			PageSize="10" AllowExport="false" Display="true">
			<Sql><![CDATA[SELECT DISTINCT Products.*, Categories.CategoryName
FROM Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID
			]]></Sql>
			<Columns>
				<Column Id="Discontinued" Type="MAPPED" MappedDataNotFound="Undefined">
					<ColumnMap Key="1" MessageKey="Active" />
					<ColumnMap Key="0" MessageKey="Discontinued" />
				</Column>
				<Column Id="SupplierID" AllowFilter="true" Type="INTEGER"/>
			</Columns>
			<GroupBy Id="ConsolidatedData" Description="Number of Product, Sum of Units in Stock and Average Units in Stock by Category">
				<GroupByColumn Id="CategoryName" RefId="CategoryName"/>
				<CalculatedColumn Id="Products" RefId="ProductID" Type="INTEGER"
					Consolidator="count" Description="#Products"/>
				<CalculatedColumn RefId="UnitsInStock" Type="INTEGER"
					Consolidator="sum" Description="#UnitsInStock" />
				<CalculatedColumn Id="AverageUnitsInStock" RefId="UnitsInStock" Type="DOUBLE"
					Consolidator="average" Description="#AverageUnitsInStock" Format="#.00"/>
				<Chart>
					<Param Name="static" Value="true"/>
				</Chart>
			</GroupBy>
		</Recordset>
	</Report>
</Reports>
