=== eduardoarantes/tears/Configurations/Test/reports/groupByReports/Report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>Esse documento faz parte do sistema de relatórios e
			não pode ser utilizado para outros fins.
			Propriedade de Trigger
			Soluções</xs:documentation>
	</xs:annotation>
	<xs:element name="Reports" type="ReportsType">
		<xs:annotation>
			<xs:documentation>Trigger Easy Application Report
				Sistema de geração
				de automática de relatórios</xs:documentation>
		</xs:annotation>
		<xs:keyref name="reportConnectionIdRefKey" refer="connectionIdKey">
			<xs:selector xpath="Report" />
			<xs:field xpath="@ConnectionId" />
		</xs:keyref>
		<xs:keyref name="defaultConnectionKey" refer="connectionIdKey">
			<xs:selector xpath="Connections" />
			<xs:field xpath="@defaultConnection" />
		</xs:keyref>
		<xs:key name="connectionIdKey">
			<xs:selector xpath=".//Connections/Connection" />
			<xs:field xpath="@Id" />
		</xs:key>
		<xs:key name="reportIdKey">
			<xs:selector xpath="Report" />
			<xs:field xpath="@Id" />
		</xs:key>
	</xs:element>
	<xs:complexType name="RecordsetParametersType">
		<xs:sequence>
			<xs:element name="RSQueryParameters" type="QueryParametersType"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QueryParametersType">
		<xs:sequence>
			<xs:element name="QueryParameter" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="QueryParameterType" />
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QueryParameterType">
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="DefaultValue" type="xs:string" use="optional" />
	</xs:complexType>
	<xs:complexType name="ReportParametersType">
		<xs:sequence>
			<xs:element name="ReportParameter" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ReportParameterType">
							<xs:sequence>
								<xs:element name="ReportParameterMap" minOccurs="0"
									maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="Key" type="xs:string" use="required" />
										<xs:attribute name="MessageKey" type="xs:string"
											use="required" />
									</xs:complexType>
								</xs:element>
								<xs:element name="ReportParameterSql" type="ReportParameterSqlType"
									maxOccurs="1" minOccurs="0">
								</xs:element>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReportParameterType">
		<xs:attribute name="Required" type="xs:string" use="optional"
			default="true" />
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="Type" type="xs:string" />
		<xs:attribute name="Description" type="xs:string" />
		<xs:attribute name="DefaultValue" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="RecordsetType">
		<xs:sequence>
			<xs:element name="Sql" type="xs:string" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="Config" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Content"
							type="xs:string" maxOccurs="1" minOccurs="0">
						</xs:element>
					</xs:sequence>
					<xs:attribute name="Name" type="xs:string"
						use="required" />
					<xs:attribute name="Value" type="xs:string"
						use="optional" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Columns" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Column" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ColumnMap" minOccurs="0"
										maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="Key" type="xs:string" use="required" />
											<xs:attribute name="MessageKey" type="xs:string"
												use="required" />
										</xs:complexType>
									</xs:element>
									<xs:element name="Url" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="UrlParameter" minOccurs="0"
													maxOccurs="unbounded">
													<xs:complexType>
														<xs:simpleContent>
															<xs:extension base="xs:string">
																<xs:attribute name="Name" type="xs:string"
																	use="required" />
															</xs:extension>
														</xs:simpleContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="ReportId" type="xs:string" />
											<xs:attribute name="Description" type="xs:string" />
											<xs:attribute name="Path" type="xs:string" />
											<xs:attribute name="Complement" type="xs:string" />
											<xs:attribute name="NewWindow" type="xs:string"
												default="false" />
											<xs:attribute name="OpenInLine" type="xs:boolean"
												use="optional" default="false">
											</xs:attribute>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="Id" type="xs:string" use="required" />
								<xs:attribute name="Description" type="xs:string"
									use="optional" />
								<xs:attribute name="Type" type="xs:string" default="TEXT" />
								<xs:attribute name="Consolidator" type="xs:string"
									use="optional" />
								<xs:attribute name="MappedDataNotFound" type="xs:string"
									use="optional" />
								<xs:attribute name="Display" type="xs:boolean" use="optional"
									default="true">
								</xs:attribute>
								<xs:attribute name="Format" type="xs:string" use="optional">
									<xs:annotation>
										<xs:documentation>
											allows to format data
										</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="StyleClass" type="xs:string">
								</xs:attribute>
								<xs:attribute name="AllowFilter" type="xs:boolean"
									default="false">
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="GroupBy" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="GroupByColumn"
							maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="RefId"
											type="xs:string" use="required">
										</xs:attribute>
										<xs:attribute name="Id"
											type="xs:string" use="optional">
										</xs:attribute>
										<xs:attribute
											name="Consolidator" type="xs:string" use="optional" />
										<xs:attribute name="Description"
											type="xs:string" use="optional">
										</xs:attribute>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="CalculatedColumn"
							minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="RefId"
											type="xs:string" use="required">
										</xs:attribute>
										<xs:attribute name="Id"
											type="xs:string" use="optional">
										</xs:attribute>
										<xs:attribute name="Type"
											type="xs:string" use="required" />
										<xs:attribute
											name="Consolidator" type="xs:string" use="optional" />
										<xs:attribute name="Description"
											type="xs:string" use="optional">
										</xs:attribute>
										<xs:attribute name="Format"
											type="xs:string">
										</xs:attribute>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="Chart" type="ChartType"
							maxOccurs="1" minOccurs="0">
						</xs:element>
					</xs:sequence>
					<xs:attribute name="Description" type="xs:string"
						use="optional" />
					<xs:attribute name="Id" type="xs:string"
						use="required" />
					<xs:attribute name="Display" type="xs:boolean"
						use="optional" default="true">
					</xs:attribute>
					<xs:attribute name="WithDetails"
						type="xs:boolean">
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Chart" maxOccurs="1" minOccurs="0"
				type="ChartType">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="Description" type="xs:string" />
		<xs:attribute name="DefaultSortColumn" type="xs:string"
			use="optional" />
		<xs:attribute name="RowCountLabel" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					se esse atributo for especificado será criada uma
					coluna com o contador de registros
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="PageSize" type="xs:int" use="optional"></xs:attribute>
		<xs:attribute name="AllowExport" type="xs:string" use="optional"
			default="">
		</xs:attribute>
		<xs:attribute name="Display" type="xs:boolean" use="optional"
			default="true">
		</xs:attribute>
		<xs:attribute name="StyleClass" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ReportsType">
		<xs:sequence>
			<xs:element name="Report" type="ReportType"
				maxOccurs="unbounded">
				<xs:key name="reportParameterIdKey">
					<xs:selector
						xpath="ReportParameters/ReportParameter" />
					<xs:field xpath="@Name" />
				</xs:key>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Version" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ReportType">
		<xs:sequence>
			<xs:element name="ReportParameters" type="ReportParametersType"
				minOccurs="0" />
			<xs:element name="Recordset" type="RecordsetType"
				minOccurs="0" maxOccurs="unbounded">
				<xs:keyref name="ReportParameterKeyRef" refer="ReportParameterKey">
					<xs:selector xpath=".//Reports/Report/Recordset/QueryParameters/*" />
					<xs:field xpath="@Name" />
				</xs:keyref>
				<xs:key name="ReportParameterKey">
					<xs:selector xpath=".//Reports/Report/ReportParameters/ReportParameter" />
					<xs:field xpath="@Name" />
				</xs:key>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Description" type="xs:string" use="optional" />
		<xs:attribute name="Id" type="xs:string" use="required" />
		<xs:attribute name="Roles" type="xs:string" use="optional" />
		<xs:attribute name="IsMainReport" type="xs:string" use="optional"
			default="true">
			<xs:annotation>
				<xs:documentation>
					used to hide detailed reports, called from other
					reports
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ExternalLink" type="xs:string" use="optional"
			default="" />
		<xs:attribute name="ConnectionId" type="xs:string" />
		<xs:attribute name="DownloadOnly" type="xs:string"
			default="none" use="optional">
		</xs:attribute>
		<xs:attribute name="TemplateName" type="xs:string"
			default="Default.html" use="optional"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ReportParameterSqlType">
		<xs:annotation>
			<xs:documentation>
				Elemento fornecido para disponibilizar uma lista de valores para
				serem passados como parametro para a query do RecordSet em questão.
				Para configurá-lo corretamente será necessário informar os valores
				dos atributos key e value. Caso não informe algum dos valores,
				o
				mesmo deve ser substituidopor alias na query dentro do
				elemento-filho sql. Exemplos:
				<ReportParameterSql>
					<sql>
		<![CDATA[
			select A as KEY, B as VALUE from c
		]]>
					</sql>
				</ReportParameterSql>
				----------------------------------------------------------
				<ReportParameterSql key="A">
					<sql>
		<![CDATA[
			select A, B as VALUE from c
		]]>
					</sql>
				</ReportParameterSql>
				----------------------------------------------------------
				<ReportParameterSql value="B">
					<sql>
		<![CDATA[
			select A as KEY, B from c
		]]>
					</sql>
				</ReportParameterSql>
				----------------------------------------------------------
				<ReportParameterSql key="A" value="B">
					<sql>
		<![CDATA[
			select A, B from c
		]]>
					</sql>
				</ReportParameterSql>
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="sql" type="xs:string">
				<xs:annotation>
					<xs:documentation></xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="key" type="xs:string"></xs:attribute>
		<xs:attribute name="value" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ParamType">		<xs:attribute name="Name" type="xs:string" use="required" />
		<xs:attribute name="Value" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="ChartType">
		<xs:sequence>
			<xs:element name="ChartColumn" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="RefId" type="xs:string" use="required" />
					<xs:attribute name="Description" type="xs:string" use="optional" />
					<xs:attribute name="Type" type="xs:string" default="TEXT" />
					<xs:attribute name="Format" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>
								allows to format data
							</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Param" type="ParamType" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Type" type="xs:string" use="optional">
		</xs:attribute>
		<xs:attribute name="Title" type="xs:string"></xs:attribute>
		<xs:attribute name="Description" type="xs:string"></xs:attribute>
		<xs:attribute name="Height" type="xs:int"></xs:attribute>
		<xs:attribute name="Width" type="xs:int"></xs:attribute>
	</xs:complexType>
</xs:schema>

=== eduardoarantes/tears/Configurations/Moodle/reports/Questionario/Reports_Questionarios_Resultados.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.1/Report.xsd"
	Version="1.0.1">
	<Report Id="ResultadoPorQuestionario" Description="Resultado por questionário" IsMainReport="true">
		<ReportParameters>
			<ReportParameter Id="quizId" Type="STRING"/>
			<ReportParameter Id="grade" Type="STRING" DefaultValue="50"/>
			<ReportParameter Id="name" Type="STRING" DefaultValue="%"/>
		</ReportParameters>
		<Recordset Id="ResultadoPorQuestionario" Description="Resultado por questionário">
			<Sql><![CDATA[
			SELECT concat( user.firstname,' ', IF(STRCMP(user.lastname,'-'),
user.lastname,'')) as fullname, 
	    		SUM(grades.grade) as grade,
	    		SUM(quiz.sumgrades) as sumgrades
          
					FROM #{table.prefix}quiz_grades AS grades,
						#{table.prefix}quiz AS quiz,
						#{table.prefix}user AS user
				
					WHERE grades.quiz =#{quizId}
						AND grades.quiz = quiz.id
						AND user.id = grades.userid
						AND round( (grades.grade / quiz.sumgrades)*100,1) < #{grade}
            			AND (user.firstname LIKE #{name} or user.lastname LIKE #{name})  
            GROUP BY 1;
			]]></Sql>
			<Chart Type="Pie">
				<ChartColumn RefId="grade"/>
			</Chart>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Test/reports/Orders/Reports_Orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0/Report.xsd" Version="1.0">
	<Report ConnectionId="jdbc/northwind" Id="OrdersByShipper"
		Description="Order by Shipper. Form to select shipper. The combo box is filled automatically. It also has a consolidator, counting the number of itens"
		>
		<ReportParameters>
			<ReportParameter Id="idShipper" Type="QUERY">
				<ReportParameterSql>
					<sql><![CDATA[
SELECT ShipperID AS "KEY" , CompanyName "VALUE" FROM Shippers
				]]></sql>
				</ReportParameterSql>
			</ReportParameter>
		</ReportParameters>
		<Recordset Id="OrdersByShipper" DefaultSortColumn="OrderID"
			Description="List of orders shipped by an specific shipper company"
			PageSize="17">
			<Sql><![CDATA[SELECT OrderID, CustomerID, EmployeeID, OrderDate, RequiredDate, 
ShippedDate, ShipVia, Freight, ShipName, ShipAddress, ShipCity, 
ShipRegion, ShipPostalCode, ShipCountry FROM Orders 
WHERE ShipVia= #{idShipper}
			]]></Sql>
			<Columns>
				<Column Consolidator="count" Id="OrderID" Type="TEXT"
					Description="Number of orders" />
				<Column Id="Freight" Type="DOUBLE" Format="#.##" />
			</Columns>
		</Recordset>
	</Report>
	<Report Id="OrdersByShipperFiltering"
		Description="Order by Shipper.">
		<Recordset Id="OrdersByShipperFiltering" DefaultSortColumn="OrderID"
			Description="List of orders shipped by an specific shipper company"
			PageSize="17">
			<Sql><![CDATA[SELECT OrderID, CustomerID, EmployeeID, OrderDate, RequiredDate, 
ShippedDate, ShipVia, Freight, ShipName, ShipAddress, ShipCity, 
ShipRegion, ShipPostalCode, ShipCountry FROM Orders 
			]]></Sql>
			<Columns>
				<Column Id="ShipVia" AllowFilter="true" />
				<Column Id="ShipCountry" AllowFilter="true" />
				<Column Id="OrderID" Display="false" />
				
			</Columns>
		</Recordset>
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Sample/reports/DrillDown/Reports_Categories.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.1/Report.xsd" Version="1.0.1">
	<Report Id="BasicDrillDown" Description="One Column with link for details">
		<Recordset Id="BasicDrillDown" DefaultSortColumn="One Column with link for details"
			Description="Click on the id number to see Product list for the category">
			<Sql><![CDATA[SELECT CategoryID, CategoryName, Description
FROM Categories
			]]></Sql>
			<Columns>
				<Column Id="CatID" Description="Ver Detalhes" Type="TEXT" Value="Detalhes">
					<Url ReportId="ProductListByCategory"
						Description="Click here to see Product list for this category">
						<UrlParameter Name="categoryID">CategoryID</UrlParameter>
					</Url>
				</Column>
				<Column Id="CategoryName" Description="Name Category" />
				<Column Id="Description" Description="Description" />
			</Columns>
		</Recordset>

	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Moodle/reports/Cursos/Reports_cursos.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0.1/Report.xsd" Version="1.0.1">
	<Report Id="ListadeCursos" Description="Lista de cursos">
		<ReportParameters>
			<ReportParameter Id="category" Description="Categoria" Type="QUERY" Required="true">
				<ReportParameterSql><sql><![CDATA[
SELECT id AS "KEY" , name "VALUE" FROM #{table.prefix}course_categories;
				]]></sql></ReportParameterSql>
			</ReportParameter>
		</ReportParameters>
		<Recordset Id="ListaDeCursos"
			Description="Lista de cursos">
			<Sql><![CDATA[
				SELECT c.id, c.shortname, c.fullname, c.idnumber, c.format, COUNT('') Alunos, c.visible
					FROM #{table.prefix}course c
					 INNER JOIN #{table.prefix}context cx ON c.id = cx.instanceid AND cx.contextlevel = '50'
					 INNER JOIN #{table.prefix}role_assignments ra ON cx.id = ra.contextid
					 INNER JOIN #{table.prefix}role r ON ra.roleid = r.id
					WHERE r.id = 5 and category= #{category}
					GROUP BY c.id; 
			]]></Sql>
			<Columns>
				<Column Id="id">
					<Url ReportId="ListadeQuestionarios" Description="Listar os questionários">
						<UrlParameter Name="course">id</UrlParameter>
					</Url>
					<Url ReportId="ListadeUsuarios" Description="Listar os usuários desse curso">
						<UrlParameter Name="course">id</UrlParameter>
					</Url>
					<Url ReportId="ForunsPorCurso" Description="Listar os fóruns desse curso">
						<UrlParameter Name="course">id</UrlParameter>
					</Url>
					<Url ReportId="ListadeDialogos" Description="Listar os dialogos desse curso">
						<UrlParameter Name="course">id</UrlParameter>
					</Url>					
				</Column>
				<Column Id="shortname" Description="Nome"/>
				<Column Id="fullname" Description="Descrição"/>
				<Column Id="visible" Description="Visível"
					MappedDataNotFound="Ainda não definido">
					<ColumnMap Key="1" MessageKey="Visível" />
					<ColumnMap Key="0" MessageKey="Oculto" />
				</Column>
				<Column Id="format" Description="Formato"/>
			</Columns>
		</Recordset>
	</Report>
	
</Reports>

=== eduardoarantes/tears/Configurations/Sample/reports/Charts/Reports_Chart.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0/Report.xsd"
	Version="1.0">
	<Report Id="ChartSampleWithTable" Description="Simple charts with table">
		<Recordset Id="DefaulChartType" Description="Default chart Type is defined to be Column" AllowExport="HTML,PDF">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Provider="google" />
		</Recordset>
	</Report>
	<Report Id="DynamicChartSample" Description="Dynamic Charts without table">
		<Recordset Id="DefaulChartType" Description="Default chart Type is defined to be Column"
			Display="false" AllowExport="HTML">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Provider="google"/>
		</Recordset>
		<Recordset Id="PieChart" Description="Pie chart" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="pie"  Provider="google"/>
		</Recordset>
		<Recordset Id="LineChart" Description="Line" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="line"  Provider="google"/>
		</Recordset>
		<Recordset Id="BarChart" Description="Ten Most Expensive Products"
			Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="bar"  Provider="google"/>
		</Recordset>
		<Recordset Id="Column" Description="Column" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="column"  Provider="google"/>
		</Recordset>
		<Recordset Id="StackedBar" Description="Column" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="bar"  Provider="google">
				<Param Name="isStacked" Value="true"/>
				<Param Name="isVertical" Value="true"/>
			</Chart>
		</Recordset>
		<Recordset Id="StackedColumn" Description="Column" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="column"  Provider="google">
				<Param Name="isStacked" Value="true"/>
			</Chart>
		</Recordset>
	</Report>

	<Report Id="StaticChartSample" Description="Static Charts without table">
		<Recordset Id="DefaulChartType" Description="Default chart Type is defined to be Column"
			Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart />
		</Recordset>
		<Recordset Id="PieChart" Description="Pie chart" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="pie"/>
		</Recordset>
		<Recordset Id="LineChart" Description="Line" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="line"/>
		</Recordset>
		<Recordset Id="BarChart" Description="Ten Most Expensive Products"
			Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="bar"/>
		</Recordset>
		<Recordset Id="Column" Description="Column" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="column"/>
		</Recordset>
		<Recordset Id="StackedBarChart" Description="Ten Most Expensive Products"
			Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="bar">
				<Param Name="isStacked" Value="true"/>
			</Chart>
		</Recordset>
		<Recordset Id="StackedColumn" Description="Column" Display="false">
			<Sql><![CDATA[SELECT DISTINCTROW ProductName AS TenMostExpensiveProducts, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel
FROM Products
ORDER BY UnitPrice DESC
LIMIT 0,5			]]></Sql>
			<Chart Type="column">
				<Param Name="isStacked" Value="true"/>
			</Chart>
		</Recordset>
		
	</Report>
</Reports>

=== eduardoarantes/tears/Configurations/Uses/reports/SupplyChain/Estoque/Reports_ProductsListByCategory.xml
<?xml version="1.0" encoding="UTF-8"?>
<Reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.triggersolucoes.com/tears/1.0/Report.xsd"
	Version="1.0">
	<Report Id="ProdutosPorCategoria" Description="Lista de produtos da categoria">
		<ReportParameters>
			<ReportParameter Id="categoryID" Type="QUERY">
				<ReportParameterSql>
					<sql><![CDATA[
					SELECT CategoryID "KEY", CategoryName "VALUE"
FROM Categories order by CategoryName
				]]></sql>
				</ReportParameterSql>
			</ReportParameter>
		</ReportParameters>
		<Recordset Id="ProdutosPorCategoria" Description="Lista de produtos da categoria">
			<Sql><![CDATA[SELECT DISTINCT Products.*, Categories.CategoryName
FROM Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID
WHERE Categories.CategoryID = #{categoryID}
			]]></Sql>
			<Columns>
				<Column Id="ProductID" Type="INTEGER" StyleClass="COLORED_NUMBER" />
				<Column Id="SupplierID" Type="INTEGER" StyleClass="COLORED_NUMBER">
					<Url ReportId="DetalheFornecedor" OpenInLine="true"
						Description="Clique aqui para ver o detalhe dos fornecedores">
						<UrlParameter Name="supplierID">SupplierID</UrlParameter>
					</Url>
				</Column>
				<Column Id="Discontinued" Description="MappedColumn" Type="TEXT"
					MappedDataNotFound="Undefined">
					<ColumnMap Key="1" MessageKey="Active" />
					<ColumnMap Key="0" MessageKey="Discontinued" />
				</Column>
			</Columns>
		</Recordset>
	</Report>
	<Report Id="DetalheFornecedor" Description="Detalhes do Fornecedor"
		IsMainReport="false">
		<ReportParameters>
			<ReportParameter Id="supplierID" Required="true"
				Description="Supplier Id" Type="INTEGER" />
		</ReportParameters>
		<Recordset Id="DetalheFornecedor" Description="Detalhes do Fornecedor"
			AllowExport="none">
			<Sql><![CDATA[SELECT SupplierID, CompanyName, ContactName, ContactTitle
, Address, City, Region, PostalCode, Country, Phone, Fax, HomePage
FROM Suppliers 
WHERE SupplierID = #{supplierID}
			]]></Sql>
		</Recordset>
	</Report>
</Reports>
